apiVersion: v1
kind: Service
metadata:
  name: microservice
spec:
  type: LoadBalancer   # change to ClusterIP if only inside cluster
  selector:
    app: microservice
  ports:
    - port: 80
      targetPort: 8080
