replicaCount: 2

image:
  repository: <sivaraj7>/microservice
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

livenessProbe:
  path: /actuator/health/liveness
  initialDelaySeconds: 20
  periodSeconds: 10

readinessProbe:
  path: /actuator/health/readiness
  initialDelaySeconds: 10
  periodSeconds: 5

nodeSelector: {}
tolerations: []
affinity: {}
